### ISSUE TITLE
Matter Custom Part Manufacturing Service  lost --serial_number ?

### ISSUE THREAD

**Issue by ifdreams** [SiliconLabs/matter#136]
### General description of the feature

How do I write "123456"  in  manufacturing  data 
Can support python3 ./provision.py  --serial_number "123456" ???

### SMG version

release_2.1.0-1.1

### Protocol(s)

Thread

### Hardware platform(s)

mg24

**Comment by silabs-sebastien** [comment]
@ifdreams If what you are looking for is about the device part number (i.e.: the device's internal serial number), you can use the provisioning script with using the -pn or --part_number argument. It is listed [here](https://github.com/SiliconLabs/matter/tree/release_2.1.0-1.1/cpms#arguments), which states:
> -pn, --part_number | optional | dec/hex | Device Part Number (Max 32 char).

This argument allows you to tell the script which part you wish to interact with when you have 2+ connected simultaneously. But, you cannot change that part number / serial number this way.

Since this is a support request (and not a bug or feature request), please post it on our community instead. You can do so [here](https://community.silabs.com/s/topic/0TO1M000000qHZgWAM/matter?language=en_US).
